[default]

# PACKAGE NAME
APPNAME = 'FOOTPRINT_PD'

# DIR TO SAVE LOGS
DIR_SAVE_LOGS = 'LOGS'

# FILENAME TO SAVE LOGS
LOG_FILENAME = 'LOG_FOOTPRINT_PD.log'

# LOGGING LEVEL
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'DEBUG'

# LOGGER INIT VARIABLE
LOGGERS = {}

[development]